require:
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

# See https://github.com/rubocop/rubocop/issues/11521
Lint/FormatParameterMismatch:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/test-prof.rb'
